// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fazkuotvyjwmxjimxqwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhemt1b3R2eWp3bXhqaW14cXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxOTMzMzQsImV4cCI6MjA3ODc2OTMzNH0.dEGr5j4j6yegpdmQkLx5LX4o3qS9DvnlT03sP9vP2eA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});